package backend.aula7;

public enum Produtos_enum {
	ARROZ, FEIJÃO, MACARRÃO, AÇÚCAR, SAL, ÓLEO, FARINHA, CAFÉ, LEITE, PÃO, MANTEIGA, MARGARINA, QUEIJO, PRESUNTO,
	IOGURTE, OVOS, FRANGO, CARNE, PEIXE, BATATA, CEBOLA, TOMATE, ALFACE, CENOURA, MAÇÂ, BANANA, LARANJA, REFRIGERANTE,
	SUCO, BISCOITO;
}
